## Dorado default:0.4.3
## FIXED PARAMETERS - DO NOT CHANGE UNLESS NEW DORADO VERSION OR MODELS
dorado_exec: '/project/spott/lizarraga/nanopore/dorado/dorado-0.4.3-linux-x64/bin/dorado'
## Dorado models. 
dorado_models_dir: '/project/spott/lizarraga/nanopore/dorado/dorado_models'
model_base: 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0'
model_6mA: 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0_6mA@v2'
model_5mC: 'dna_r10.4.1_e8.2_400bps_sup@v4.2.0_5mC@v2'

